### ISSUE TITLE
Scrolling doesn't work in creative menu

### ISSUE THREAD

**Issue by Julienraptor01** [ADON15c/Scrollable-Tooltips#1]
I've installed this mod and only this mod and i sadly cannot get it to work.
I've used Fabric Loader 0.14.6 and Fabric API 0.53.0.
This is the item i used for testing :
`give @p stick{display:{Lore:['{"text":"Lorem"}','{"text":"ipsum"}','{"text":"dolor"}','{"text":"sit"}','{"text":"amet,"}','{"text":"consectetur"}','{"text":"adipiscing"}','{"text":"elit."}','{"text":"Proin"}','{"text":"interdum"}','{"text":"euismod"}','{"text":"ultrices."}','{"text":"Proin"}','{"text":"tincidunt"}','{"text":"lobortis"}','{"text":"magna"}','{"text":"et"}','{"text":"condimentum."}','{"text":"Ut"}','{"text":"et"}','{"text":"nisi"}','{"text":"luctus,"}','{"text":"imperdiet"}','{"text":"metus"}','{"text":"et,"}','{"text":"sodales"}','{"text":"tortor."}','{"text":"In"}','{"text":"venenatis"}','{"text":"malesuada"}','{"text":"arcu"}','{"text":"at"}','{"text":"volutpat."}','{"text":"Donec"}','{"text":"facilisis"}','{"text":"eros"}','{"text":"vel"}','{"text":"felis"}','{"text":"porttitor,"}','{"text":"sed"}','{"text":"elementum"}','{"text":"odio"}','{"text":"sodales."}','{"text":"Nunc"}','{"text":"nisi"}','{"text":"quam,"}','{"text":"sodales"}','{"text":"vitae"}','{"text":"imperdiet"}','{"text":"eu,"}','{"text":"ornare"}','{"text":"ultricies"}','{"text":"mi."}','{"text":"Sed"}','{"text":"dapibus"}','{"text":"et"}','{"text":"nisl"}','{"text":"at"}','{"text":"pellentesque."}','{"text":"Pellentesque"}','{"text":"porta"}','{"text":"suscipit"}','{"text":"nisi"}','{"text":"quis"}','{"text":"bibendum."}','{"text":"Maecenas"}','{"text":"lacinia,"}','{"text":"lectus"}','{"text":"eget"}','{"text":"suscipit"}','{"text":"consequat,"}','{"text":"orci"}','{"text":"justo"}','{"text":"facilisis"}','{"text":"ligula,"}','{"text":"a"}','{"text":"feugiat"}','{"text":"tortor"}','{"text":"sem"}','{"text":"eu"}','{"text":"dui."}','{"text":"Maecenas"}','{"text":"aliquet,"}','{"text":"metus"}','{"text":"id"}','{"text":"vulputate"}','{"text":"maximus,"}','{"text":"magna"}','{"text":"orci"}','{"text":"aliquet"}','{"text":"tellus,"}','{"text":"in"}','{"text":"aliquet"}','{"text":"est"}','{"text":"leo"}','{"text":"faucibus"}','{"text":"urna."}','{"text":"Nunc"}','{"text":"mattis"}','{"text":"ex"}','{"text":"eget"}','{"text":"massa"}','{"text":"euismod,"}','{"text":"ac"}','{"text":"pulvinar"}','{"text":"sem"}','{"text":"iaculis."}','{"text":"Phasellus"}','{"text":"vel"}','{"text":"tellus"}','{"text":"id"}','{"text":"nisi"}','{"text":"consectetur"}','{"text":"dapibus"}','{"text":"sed"}','{"text":"eget"}','{"text":"mi."}','{"text":"Phasellus"}','{"text":"eu"}','{"text":"libero"}','{"text":"facilisis,"}','{"text":"aliquet"}','{"text":"felis"}','{"text":"non,"}','{"text":"pulvinar"}','{"text":"leo."}','{"text":"Pellentesque"}','{"text":"et"}','{"text":"magna"}','{"text":"ac"}','{"text":"diam"}','{"text":"posuere"}','{"text":"mollis."}','{"text":"Nunc"}','{"text":"in"}','{"text":"aliquam"}','{"text":"orci."}','{"text":"Suspendisse"}','{"text":"finibus"}','{"text":"leo"}','{"text":"vitae"}','{"text":"ex"}','{"text":"faucibus,"}','{"text":"quis"}','{"text":"scelerisque"}','{"text":"velit"}','{"text":"efficitur."}','{"text":"Maecenas"}','{"text":"vel"}','{"text":"blandit"}','{"text":"ante."}','{"text":"Etiam"}','{"text":"convallis"}','{"text":"rhoncus"}','{"text":"lorem"}','{"text":"et"}','{"text":"tincidunt."}','{"text":"In"}','{"text":"dapibus"}','{"text":"nisl"}','{"text":"justo,"}','{"text":"eu"}','{"text":"pellentesque"}','{"text":"erat"}','{"text":"ultrices"}','{"text":"ut."}','{"text":"Orci"}','{"text":"varius"}','{"text":"natoque"}','{"text":"penatibus"}','{"text":"et"}','{"text":"magnis"}','{"text":"dis"}','{"text":"parturient"}','{"text":"montes,"}','{"text":"nascetur"}','{"text":"ridiculus"}','{"text":"mus."}','{"text":"In"}','{"text":"sagittis"}','{"text":"bibendum"}','{"text":"elementum."}','{"text":"Nunc"}','{"text":"sit"}','{"text":"amet"}','{"text":"arcu"}','{"text":"vel"}','{"text":"mi"}','{"text":"rhoncus"}','{"text":"feugiat"}','{"text":"varius"}','{"text":"non"}','{"text":"ligula."}','{"text":"Ut"}','{"text":"eleifend"}','{"text":"dolor"}','{"text":"eu"}','{"text":"augue"}','{"text":"semper"}','{"text":"aliquam."}','{"text":"Aliquam"}','{"text":"erat"}','{"text":"volutpat."}','{"text":"Quisque"}','{"text":"sagittis"}','{"text":"leo"}','{"text":"quis"}','{"text":"elementum"}','{"text":"scelerisque."}','{"text":"Sed"}','{"text":"molestie"}','{"text":"tempor"}','{"text":"felis"}','{"text":"sit"}','{"text":"amet"}','{"text":"fermentum."}','{"text":"In"}','{"text":"eget"}','{"text":"dolor"}','{"text":"finibus,"}','{"text":"feugiat"}','{"text":"nisi"}','{"text":"ac,"}','{"text":"pretium"}','{"text":"justo."}','{"text":"Donec"}','{"text":"faucibus"}','{"text":"erat"}','{"text":"ac"}','{"text":"nisi"}','{"text":"mollis,"}','{"text":"congue"}','{"text":"vestibulum"}','{"text":"quam"}','{"text":"tincidunt."}','{"text":"Morbi"}','{"text":"tellus"}','{"text":"orci,"}','{"text":"eleifend"}','{"text":"euismod"}','{"text":"augue"}','{"text":"sit"}','{"text":"amet,"}','{"text":"ultrices"}','{"text":"tempor"}','{"text":"mi."}','{"text":"Donec"}','{"text":"elementum"}','{"text":"est"}','{"text":"at"}','{"text":"tincidunt"}','{"text":"consectetur."}','{"text":"Nulla"}','{"text":"ac"}','{"text":"nisi"}','{"text":"in"}','{"text":"mi"}','{"text":"venenatis"}','{"text":"cursus"}','{"text":"vitae"}','{"text":"ornare"}','{"text":"odio."}','{"text":"Sed"}','{"text":"blandit"}','{"text":"libero"}','{"text":"vel"}','{"text":"lectus"}','{"text":"tincidunt"}','{"text":"suscipit."}','{"text":"Nam"}','{"text":"vestibulum"}','{"text":"est"}','{"text":"sem,"}','{"text":"vitae"}','{"text":"accumsan"}','{"text":"mi"}','{"text":"accumsan"}','{"text":"malesuada."}','{"text":"In"}','{"text":"hac"}','{"text":"habitasse"}','{"text":"platea"}','{"text":"dictumst."}','{"text":"Phasellus"}','{"text":"sodales"}','{"text":"commodo"}','{"text":"sem,"}','{"text":"feugiat"}','{"text":"placerat"}','{"text":"leo"}','{"text":"auctor"}','{"text":"at."}','{"text":"Phasellus"}','{"text":"molestie"}','{"text":"at"}','{"text":"nunc"}','{"text":"non"}','{"text":"posuere."}','{"text":"Sed"}','{"text":"volutpat"}','{"text":"et"}','{"text":"odio"}','{"text":"a"}','{"text":"tempus."}','{"text":"Proin"}','{"text":"maximus,"}','{"text":"dui"}','{"text":"mattis"}','{"text":"consequat"}','{"text":"fermentum,"}','{"text":"tortor"}','{"text":"metus"}','{"text":"rhoncus"}','{"text":"augue,"}','{"text":"in"}','{"text":"hendrerit"}','{"text":"est"}','{"text":"augue"}','{"text":"sit"}','{"text":"amet"}','{"text":"justo."}','{"text":"Donec"}','{"text":"eu"}','{"text":"ipsum"}','{"text":"lacinia,"}','{"text":"facilisis"}','{"text":"justo"}','{"text":"in,"}','{"text":"congue"}','{"text":"neque."}','{"text":"In"}','{"text":"tincidunt,"}','{"text":"mauris"}','{"text":"vel"}','{"text":"sagittis"}','{"text":"euismod,"}','{"text":"ex"}','{"text":"ante"}','{"text":"vulputate"}','{"text":"orci,"}','{"text":"nec"}','{"text":"luctus"}','{"text":"massa"}','{"text":"arcu"}','{"text":"id"}','{"text":"neque."}','{"text":"Mauris"}','{"text":"euismod"}','{"text":"quis"}','{"text":"tellus"}','{"text":"non"}','{"text":"hendrerit."}','{"text":"Proin"}','{"text":"vitae"}','{"text":"fringilla"}','{"text":"felis,"}','{"text":"eget"}','{"text":"pretium"}','{"text":"leo."}','{"text":"Donec"}','{"text":"sit"}','{"text":"amet"}','{"text":"ante"}','{"text":"metus."}','{"text":"Aliquam"}','{"text":"cursus"}','{"text":"lobortis"}','{"text":"magna,"}','{"text":"quis"}','{"text":"dapibus"}','{"text":"leo"}','{"text":"volutpat"}','{"text":"ac."}','{"text":"Aliquam"}','{"text":"elementum"}','{"text":"bibendum"}','{"text":"neque,"}','{"text":"ut"}','{"text":"hendrerit"}','{"text":"diam"}','{"text":"fringilla"}','{"text":"at."}','{"text":"Maecenas"}','{"text":"ac"}','{"text":"fringilla"}','{"text":"turpis,"}','{"text":"eu"}','{"text":"elementum"}','{"text":"eros."}','{"text":"Proin"}','{"text":"sem"}','{"text":"augue,"}','{"text":"convallis"}','{"text":"nec"}','{"text":"enim"}','{"text":"ut,"}','{"text":"ornare"}','{"text":"faucibus"}','{"text":"quam."}','{"text":"Fusce"}','{"text":"iaculis"}','{"text":"nec"}','{"text":"ligula"}','{"text":"at"}','{"text":"commodo."}','{"text":"Praesent"}','{"text":"blandit"}','{"text":"ornare"}','{"text":"congue."}','{"text":"Donec"}','{"text":"a"}','{"text":"laoreet"}','{"text":"risus."}','{"text":"Maecenas"}','{"text":"gravida"}','{"text":"augue"}','{"text":"non"}','{"text":"pretium"}','{"text":"blandit."}']}}`

**Comment by ADON15c** [comment]
What menu did u try this on? I know there's an issue with screens that already implement scrolling (such as the creative menu) conflicting with tooltip scrolling, maybe this is whats happening for you?

**Comment by Julienraptor01** [comment]
> What menu did u try this on? I know there's an issue with screens that already implement scrolling (such as the creative menu) conflicting with tooltip scrolling, maybe this is whats happening for you?

I was in creative mode but in my inventory where you can see your armor.

**Comment by ADON15c** [comment]
Alright, I think I'll have time to look into it sometime today

**Comment by Julienraptor01** [comment]
I already did know about this mod that does the same thing https://github.com/Provismet/Tooltip-Scroll-Fabric/issues/2 but sadly it isn't officially available for 1.18.2 and i need to use a fork and it isn't on mod hosting platform like modrinth and i was hoping that your mod could replace it.
So it might interest you to take a look at it as it doesn't have the same issue.

**Comment by ADON15c** [comment]
Oh thanks, I wasn't aware of another one. I'll take a look at it later

**Comment by ADON15c** [comment]
Changed it so the scrolling still works in any creative inventory tab that doesn't already have a scroll bar, should work better now. I'll publish a new build with the fix soon
